name: Doxygen Action

on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "docs/doxygen/" # default is .

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/doxygen/html
        cname: sdk.resilientdb.com
